# Generated by Django 4.0 on 2022-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickandrent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteusers',
            old_name='password',
            new_name='inputEmail',
        ),
        migrations.RenameField(
            model_name='websiteusers',
            old_name='username',
            new_name='inputLastName',
        ),
        migrations.AddField(
            model_name='websiteusers',
            name='inputName',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteusers',
            name='inputPassword',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
    ]
