# Generated by Django 4.0 on 2022-05-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickandrent', '0002_rename_password_websiteusers_inputemail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='websiteUsers',
        ),
    ]
