# Generated by Django 4.0 on 2022-05-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickandrent', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ads',
            new_name='Ad',
        ),
    ]
