# Generated by Django 4.0 on 2022-05-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickandrent', '0005_rename_ads_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
