# Generated by Django 4.0 on 2022-05-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickandrent', '0006_ad_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
